apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dr-data
  namespace: dr-demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 5Gi
